import { SITE } from '@/shared/config';

export const siteJsonLd = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'WebSite',
      '@id': `${SITE.url}/#website`,
      url: SITE.url,
      name: SITE.name,
      description: SITE.description,
      inLanguage: SITE.lang,
      publisher: { '@id': `${SITE.url}/#author` },
    },
    {
      '@type': 'Person',
      '@id': `${SITE.url}/#author`,
      name: 'Alexandr Artemev',
      url: SITE.url,
    },
    {
      '@type': 'SoftwareApplication',
      '@id': `${SITE.url}/#app`,
      name: SITE.name,
      url: SITE.url,
      description: SITE.description,
      applicationCategory: 'CommunicationApplication',
      applicationSubCategory: 'Voice and video conferencing',
      operatingSystem: 'Web, Windows, macOS, Linux',
      browserRequirements: 'Requires a browser with WebRTC support',
      softwareHelp: `${SITE.url}/#faq`,
      isAccessibleForFree: true,
      inLanguage: [SITE.lang, SITE.en.lang],
      author: { '@id': `${SITE.url}/#author` },
      creator: { '@id': `${SITE.url}/#author` },
      publisher: { '@id': `${SITE.url}/#author` },
      offers: {
        '@type': 'Offer',
        price: '0',
        priceCurrency: 'USD',
        availability: 'https://schema.org/InStock',
      },
      featureList: [
        'Real-time voice rooms',
        'Real-time video rooms',
        'Screen sharing',
        'Text chat with file attachments',
        'Password-protected private rooms',
        'Global shortcuts and push-to-talk on desktop',
        'Email sign-in',
        'Native desktop app for Windows, macOS and Linux',
        'Self-hostable open source project',
      ],
    },
  ],
} as const;
