import { z } from 'zod';

export const apiErrorCodeSchema = z.enum([
  'INTERNAL_ERROR',
  'VALIDATION_FAILED',
  'UNAUTHORIZED',
  'FORBIDDEN',

  'ROOM_NOT_FOUND',
  'ROOM_NAME_TAKEN',
  'ROOM_NAME_INVALID',
  'ROOM_PASSWORD_REQUIRED',
  'ROOM_PASSWORD_INVALID',

  'USER_NOT_FOUND',
  'DISPLAY_NAME_INVALID',

  'MESSAGE_NOT_FOUND',
  'MESSAGE_NOT_OWNED',

  'FRIENDSHIP_NOT_FOUND',
  'FRIEND_REQUEST_NOT_FOUND',
  'FRIEND_REQUEST_EXISTS',
  'FRIEND_REQUEST_INCOMING_EXISTS',
  'FRIEND_REQUEST_NOT_CANCELABLE',
  'FRIEND_ALREADY',
  'FRIEND_SELF',

  'DM_SELF',
  'DM_NOT_FRIENDS',

  'FILE_EMPTY',
  'FILE_TOO_LARGE',
  'FILE_NOT_IMAGE',
  'IMAGE_TOO_LARGE',
  'SCREENSHOT_TOO_LARGE',

  'WEBHOOK_SIGNATURE_INVALID',
]);

export const apiErrorSchema = z.object({
  error: z.string(),
  code: apiErrorCodeSchema.catch('INTERNAL_ERROR'),
});
