import { z } from 'zod';

export const apiErrorCodeSchema = z.enum([
  'INTERNAL_ERROR',
  'VALIDATION_FAILED',
  'UNAUTHORIZED',
  'FORBIDDEN',

  'ROOM_NOT_FOUND',
  'ROOM_NAME_TAKEN',
  'ROOM_NAME_INVALID',
  'ROOM_PASSWORD_REQUIRED',
  'ROOM_PASSWORD_INVALID',
  'ROOM_ACCESS_DENIED',

  'USER_NOT_FOUND',
  'DISPLAY_NAME_INVALID',

  'MESSAGE_NOT_FOUND',
  'MESSAGE_NOT_OWNED',

  'FRIENDSHIP_NOT_FOUND',
  'FRIEND_REQUEST_NOT_FOUND',
  'FRIEND_REQUEST_EXISTS',
  'FRIEND_REQUEST_INCOMING_EXISTS',
  'FRIEND_REQUEST_NOT_CANCELABLE',
  'FRIEND_ALREADY',
  'FRIEND_SELF',

  'DM_SELF',
  'DM_NOT_FRIENDS',

  'CALL_ALREADY_RINGING',

  'USER_BLOCKED',
  'ABUSE_TARGET_NOT_FOUND',
  'ABUSE_SELF_REPORT',
  'ABUSE_REPORT_NOT_FOUND',
  'ABUSE_ALREADY_REPORTED',
  'BLOCK_SELF',
  'BLOCK_ADMIN',
  'ADMIN_ONLY',

  'INVALID_EMAIL_OR_PASSWORD',
  'INVALID_EMAIL',
  'INVALID_PASSWORD',
  'INVALID_TOKEN',
  'TOKEN_EXPIRED',
  'EMAIL_NOT_VERIFIED',
  'EMAIL_ALREADY_VERIFIED',
  'USER_ALREADY_EXISTS',
  'USER_ALREADY_EXISTS_USE_ANOTHER_EMAIL',
  'USER_ALREADY_HAS_PASSWORD',
  'PASSWORD_ALREADY_SET',
  'ACCOUNT_NOT_FOUND',
  'INVALID_USER',
  'EMAIL_CAN_NOT_BE_UPDATED',
  'CHANGE_EMAIL_DISABLED',
  'SESSION_NOT_FRESH',
  'VERIFICATION_EMAIL_NOT_ENABLED',
  'FAILED_TO_CREATE_USER',
  'FAILED_TO_UPDATE_USER',
  'FAILED_TO_CREATE_SESSION',
  'USER_EMAIL_NOT_FOUND',
  'PASSWORD_TOO_SHORT',
  'PASSWORD_TOO_LONG',
  'SESSION_EXPIRED',
  'CREDENTIAL_ACCOUNT_NOT_FOUND',

  'FILE_EMPTY',
  'FILE_TOO_LARGE',
  'FILE_NOT_IMAGE',
  'IMAGE_TOO_LARGE',
  'SCREENSHOT_TOO_LARGE',

  'WEBHOOK_SIGNATURE_INVALID'
]);

export const apiErrorSchema = z.object({
  error: z.string(),
  code: apiErrorCodeSchema.catch('INTERNAL_ERROR')
});
