import type { LucideIcon } from 'lucide-react';

import {
  AppWindow,
  AudioLines,
  AudioWaveform,
  BellRing,
  Clock,
  Compass,
  Crown,
  DoorOpen,
  Gamepad2,
  Keyboard,
  Link2,
  MessageSquareText,
  Mic,
  MonitorDown,
  Paperclip,
  PartyPopper,
  PencilLine,
  PhoneCall,
  PictureInPicture2,
  Radio,
  Ratio,
  ScreenShare,
  ShieldCheck,
  Signal,
  SlidersHorizontal,
  Sparkles,
  SquareMenu,
  SquarePen,
  TabletSmartphone,
  UserPlus,
  Users,
  Video
} from 'lucide-react';

import type { FeaturesItemKey } from './groups';

export const FEATURES_ITEM_ICONS: Record<FeaturesItemKey, LucideIcon> = {
  background: PictureInPicture2,
  activity: Gamepad2,
  rooms: Sparkles,
  video: Video,
  screen: ScreenShare,
  quality: Signal,
  volume: SlidersHorizontal,
  gate: Mic,
  ptt: Radio,
  shortcuts: Keyboard,
  devices: AudioLines,
  processing: AudioWaveform,
  chatInRoom: MessageSquareText,
  markdown: SquarePen,
  attachments: Paperclip,
  editing: PencilLine,
  reactions: PartyPopper,
  friendList: Users,
  requests: UserPlus,
  presence: Compass,
  directCalls: PhoneCall,
  notifications: BellRing,
  publicRooms: DoorOpen,
  privateRooms: ShieldCheck,
  invites: Link2,
  recent: Clock,
  ownership: Crown,
  web: AppWindow,
  desktop: MonitorDown,
  tray: SquareMenu,
  android: TabletSmartphone,
  safeArea: Ratio
};
