export {
  CONTRIBUTORS_CACHE_TTL_MS,
  CONTRIBUTORS_PER_PAGE,
  DESKTOP_TAG_PREFIXES,
  headers,
  MOBILE_TAG_PREFIXES,
  RELEASES_CACHE_TTL_MS,
  REPO,
  REQUEST_TIMEOUT_MS,
  UNIFIED_TAG_RE
} from './github.config';
