export const SITE = {
  url: 'https://chatovo.ru',
  name: 'Chatovo',
  title: 'Chatovo — голосовые и видеокомнаты в реальном времени',
  description:
    'Бесплатные голосовые и видеокомнаты в браузере. Создайте комнату за секунды, отправьте ссылку — и общайтесь: голос, видео, демонстрация экрана. Без установки и регистрации сервера.',
  locale: 'ru_RU',
  lang: 'ru-RU',
  themeColor: {
    light: '#ffffff',
    dark: '#0a0a0a',
  },
  social: {
    twitter: '@chatovo',
  },
  keywords: [
    'Chatovo',
    'Чатово',
    'голосовой чат',
    'видеочат',
    'голосовые комнаты',
    'видеокомнаты',
    'общение голосом',
    'групповой звонок',
    'звонки в браузере',
    'приватные комнаты',
    'комнаты с паролем',
    'аналог Discord',
    'Дискорд аналог',
    'бесплатный голосовой чат',
    'WebRTC',
    'LiveKit',
  ],
  en: {
    title: 'Chatovo — Real-time voice & video rooms',
    description:
      'Free voice and video rooms that run in your browser. Create a room in seconds, share the link, and talk — with screen sharing and chat. No install, no server setup.',
    locale: 'en_US',
    lang: 'en-US',
    keywords: [
      'Chatovo',
      'voice chat',
      'video chat',
      'voice rooms',
      'video rooms',
      'WebRTC',
      'group call',
      'private rooms',
      'password protected rooms',
      'Discord alternative',
      'self-hosted chat',
      'LiveKit',
      'real-time communication',
      'voice messenger',
      'desktop voice chat',
    ],
  },
} as const;
