export const SITE = {
  url: 'https://chatovo.ru',
  name: 'Chatovo',
  title: 'Chatovo — голосовые и видеокомнаты в реальном времени',
  description:
    'Chatovo — мессенджер с голосовыми и видеокомнатами. Создайте комнату в один клик, отправьте ссылку друзьям и общайтесь — в браузере или в приложении для компьютера. Бесплатно, без установки.',
  locale: 'ru_RU',
  lang: 'ru-RU',
  themeColor: {
    light: '#ffffff',
    dark: '#0a0a0a',
  },
  social: {
    twitter: '@chatovo',
  },
  keywords: [
    'Chatovo',
    'Чатово',
    'голосовой чат',
    'видеочат',
    'голосовые комнаты',
    'видеокомнаты',
    'общение голосом',
    'групповой звонок',
    'звонки в браузере',
    'приватные комнаты',
    'комнаты с паролем',
    'аналог Discord',
    'Дискорд аналог',
    'бесплатный голосовой чат',
    'WebRTC',
    'LiveKit',
  ],
  en: {
    title: 'Chatovo — Real-time voice & video rooms',
    description:
      'Chatovo is a modern, Discord-inspired messenger built around private voice and video rooms. Spin up a room in one click, share the link, and start talking — in the browser or on the desktop.',
    locale: 'en_US',
    lang: 'en-US',
    keywords: [
      'Chatovo',
      'voice chat',
      'video chat',
      'voice rooms',
      'video rooms',
      'WebRTC',
      'group call',
      'private rooms',
      'password protected rooms',
      'Discord alternative',
      'self-hosted chat',
      'LiveKit',
      'real-time communication',
      'voice messenger',
      'desktop voice chat',
    ],
  },
} as const;
