export { KONAMI_SEQUENCE, SECRET_CLICK_COUNT, SECRET_CLICK_RESET_MS } from './config';
export {
  SNAKE_BEST_STORAGE_KEY,
  SNAKE_GRID,
  SNAKE_INITIAL,
  SNAKE_INITIAL_FOOD,
  SNAKE_KEY_TO_DIRECTION,
  SNAKE_OPPOSITE,
  SNAKE_STEP,
  SNAKE_SWIPE_THRESHOLD,
  SNAKE_TICK_MS
} from './snake';
